### PR TITLE
JENKINS-12744 - Execute a command before timeout

### PR DESCRIPTION
**Pull request by jcarsique**
Allow execution of a Shell or Batch command just before the effective thread interruption.

### CODE REVIEW

**Comment by EoinGriffin-AI** [comment]
What ever happened to this feature?

This is very useful, and I'd love to use it. Due to the age of this PR, I wonder is this code still relevant or would I be wasting my time trying to resolve these conflicts?

**Comment by kutzi** [comment]
That'd definitely be useful. I know @ikedam has done some work on this plugin lately, so maybe he feels more responsible.

From my point of view all the comments I had earlier on this are still not addresses. Especially:
- clarify where to run the command (master and/or slave) and maybe make this configurable
- why /bin/bash? This wouldn't work at all on Windows e.g.
  - if possible it would be good if the existing Jenkins support for shell/batch execution could be reused. I.e. the one in the build steps

**Comment by EoinGriffin-AI** [comment]
After posting this last week, I accidentally stumbled upon a hidden feature of the build timeout plugin.

> Manage Jenkins > Configure System > Build-timeout Plugin > BuildStep Action > Enable BuildStep Action

The BuildStep action can be any build step, including running a shell script or a windows batch command.

I'm not sure why this feature was so hidden, it's very useful.

**Comment by dudaerich** [comment]
Could someone clarify me what is difference between _Enable BuildStep Action_ (as @EoinGriffin-AI described it in previous comment) and this pull request? Did someone else implement the feature and hence this is redundant?

And do you know why the _Enable BuildStep Action_ has following note?

```
This feature is provided as-is and not supported even it does not work correct with some build steps.
```

**Comment by olivergondza** [comment]
IMO this PR should be closed as the existing feature seems more general to me.

**Comment by JSoet** [comment]
The existing feature is probably more general than this PR, but this PR I think was supposed to make it possible to execute a command before the build is aborted.
(also, it's tracked in this issue: https://issues.jenkins-ci.org/browse/JENKINS-12744)

**Comment by olivergondza** [comment]
Looking into the code the actions might not involve aborting at all or the abort action can be put anywhere in the list of actions permitting both abort-first and abort-last semantics. Or does it not?

I am closing this PR as it does not seem to be needed for now.

**Comment by PhRX** [comment]
A solution for [JENKINS-12744](https://issues.jenkins-ci.org/browse/JENKINS-12744) is still needed. 
Whether through this PR or some other solution I leave in the middle. But ATM I'm being forced to drop timeouts simply because the devs need to be able to get a jstack dump from hanging tests, and I don't see any way in Jenkins pipelines to get this functionality.

**Pull request closed without merging**
