### PR TITLE
Use JUnit 4 consistently

### PR DESCRIPTION
**Pull request by darxriggs**
- use `@Test` annotation only instead of "test" prefix (JUnit 3) or annotation mixed with prefix
- use `JenkinsRule` instead of `HudsonTestCase` (JUnit 3)
- use `TemporaryFolder` instead of manual temporary folder handling

### CODE REVIEW

**Comment by darxriggs** [comment]
@ikedam can you please exactly describe what is missing in your opinion? I think I provided all required information.

The title exactly describes what this pull request is about - "consistency". It makes all tests consistently use JUnit 4 and its features.

The description and commit comment contains all details summarized in a way to get a quick overview of the changes.

**Comment by ikedam** [comment]
Background: https://github.com/jenkinsci/build-timeout-plugin/pull/72#issuecomment-562893390

**Comment by krisstern** [comment]
Thanks @darxriggs for this PR! I think the changes are desirable and will highly likely approve and merge this PR after some more careful reviewing. Appreciate it! 

Although I will have to admit by 2022 it is perhaps time to upgrade to JUnit 5 soon. There will be a new issue coming out regarding this over the next week or so.

**Review by krisstern — APPROVED** [review]
Everything looks good in this PR

**Review by ikedam — APPROVED** [review]

**Pull request merged**
