### PR TITLE
Release/1.16.1

### PR DESCRIPTION
**Pull request by oleg-nenashev**
@ikedam It was an urgent fix to suppress the wrong version in the update center.
No actual changes have been integrated. CC @daniel-beck and @bsideup

### CODE REVIEW

**Comment by ikedam** [comment]
Thanks for the release.
I'll just close this request as it's useless to merge this change.
(Developers can track this change from a branch or the tag)

I plan to make a new release 1.17 including #54 this weekend.

**Comment by ikedam** [comment]
Hmm... the wiki page still points 1.16-INTEL-1...

**Comment by oleg-nenashev** [comment]
@ikedam No idea, maybe it's a version number sorting issue. 1.17 could be an ultimate solution, but...

**Comment by ikedam** [comment]
The wiki page now displays 1.16.1.
The update center in Jenkins also lists 1.16.1.
Thank you!

**Pull request closed without merging**
