### PR TITLE
Use HTTPS for URLs in pom.xml

### PR DESCRIPTION
**Pull request by darxriggs**
This changes all URLs in pom.xml from HTTP to HTTPS so humans and machines can make sure data is encrypted in transit.

### CODE REVIEW

**Comment by darxriggs** [comment]
@ikedam can you have a look at this pull request and my other ones following it?

**Comment by ikedam** [comment]
@darxriggs 
Please describe why you want those changes merged. For example, what problems are fixed with those changes.

**Comment by darxriggs** [comment]
@ikedam I updated the description. Please have a look again.

**Comment by ikedam** [comment]
@darxriggs Sorry for my slow response.
I want to clarify what this change affects.
Do you know how those information is used?

**Comment by darxriggs** [comment]
The license URL is for example contained in the JAR file in `WEB-INF/licenses.xml` and then provided to the user under "Manage Jenkins - About Jenkins".

The documentation URL is for example used to generate the documentation at https://plugins.jenkins.io/build-timeout page. For more details see https://jenkins.io/doc/developer/publishing/documentation/.

**Comment by ikedam** [comment]
Note: Those old URLs are redirected to new ones, and the current version still work correct. This is not a bug fix but just an improvement.

**Comment by ikedam** [comment]
Released in build-timeout-1.19.1.

**Pull request merged**
